2025-01-13 21:29:42,755 - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\PyCharmProject\education\module\module_12\module_12_4.py", line 59, in test_walk
    runner = Runner("Роман")
             ^^^^^^^^^^^^^^^
  File "D:\PyCharmProject\education\module\module_12\module_12_4.py", line 13, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2025-01-13 21:29:42,765 - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\PyCharmProject\education\module\module_12\module_12_4.py", line 59, in test_walk
    runner = Runner("Роман")
             ^^^^^^^^^^^^^^^
  File "D:\PyCharmProject\education\module\module_12\module_12_4.py", line 13, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
